name: CI/CD using github
on: push
jobs:
    CICD:
       runs-on: ubuntu-latest
       steps:
           - name: installing java
             uses: actions/setup-java@v3
             with:
             java-version: '17'
             distribution: 'temurin'
     
           - name: check
             run: |
             java -version
             javac -version1

           - name: 4. Clone Project
             uses: actions/checkout@v3

           - name: 3. Compile Java Console App Project
             run: javac WelcomeWorld.java

           - name: 4. Check Class Generated
             run: ls -ltra

           - name: 5. Run Java Console App Project
             run: java WelcomeWorld
            